package com.bkpasa.kafkastream.domain.model;

public enum AlertType {
    LIABILITY_ALERT,
    LIABILITY_ACTION,
    STAKE_DISTRIBUTION_ALERT,
    TRJ_LIMIT_ALERT,
    OVERROUND_LIMIT_ALERT,
    WDW_AND_WDWH_PRICE_ALERT,
    SCORE_DECREASE_ALERT,
    MARKET_OPEN_FROM_AN_ENDED_PERIOD_ALERT,
    SUPERVISOR_TENNIS_SERVER_MARKER,
    TENNIS_SERVER_HAS_LOWER_ODDS_ALERT,
    TENNIS_SERVER_ODDS_LIMIT_ALERT,
    GOALS_BY_INTERVAL_GOAL_SCORED_ALERT,
    GOALS_BY_INTERVAL_CLOCK_ADVANCED_ALERT,
    SUPERVISED,
    TRADED,
    LAST_TRADED,
    OPEN_IN_SUPERVISOR_CONSOLE,
    OPEN_IN_INRUNNING_MANAGER
}
